import type { Operation, Snapshot } from "../shared/types";

/**
 * A "createWindow" operation.  Not yet generated by the diff algorithm,
 * but reserved here so the planner is ready for future use.
 * If needed, one can be produced before the plan step.
 */
export type WindowOperation =
  | { kind: "createWindow"; windowId: number };

type Stage =
  | "createWindow"
  | "create"
  | "crossWindowMove"
  | "sameWindowMove"
  | "group"
  | "assignFolder"
  | "navigate"
  | "bookmark"
  | "saveForLater"
  | "close"
  | "discard"
  | "restoreFromSaved";

const STAGE_ORDER: Stage[] = [
  "createWindow",
  "create",
  "crossWindowMove",
  "sameWindowMove",
  "group",
  "assignFolder",
  "navigate",
  "bookmark",
  "saveForLater",
  "close",
  "discard",
  "restoreFromSaved",
];

/**
 * Reorder operations into a safe dependency order so that:
 *
 *   1. **createWindow**  – windows must exist before tabs can be created in them
 *   2. **create**        – tabs must exist before they can be moved, grouped, etc.
 *   3. **crossWindowMove** – get each tab to the correct window *before*
 *                            same-window reordering so the index is meaningful
 *   4. **sameWindowMove**  – finalise positions; all tabs are now where they belong
 *   5. **group**           – grouping depends on the tab existing; position is
 *                            already settled so the visual result is stable
 *   6. **assignFolder**    – metadata only, no browser tab API involved;
 *                            safe to do at any point after the tab exists
 *   7. **navigate**        – last structural change; avoids refreshing a tab while
 *                            it is still being moved/grouped, which would waste
 *                            a network load.  Also ensures the final URL is loaded
 *                            after the tab is in its permanent position.
 *   8. **bookmark**        – data-only; ordering is flexible, but placing it
 *                            after navigate means the bookmarked URL is the
 *                            final one the user intended.
 *   9. **saveForLater**    – destructive (closes the tab).  Must be after all
 *                            other tab-state changes so nothing tries to touch
 *                            a removed tab.
 *  10. **close**           – frees the tabId so it can be reused.  Must be last
 *                            because every other operation needs the tab alive.
 *  11. **discard**         – final housekeeping on tabs that survive; must be
 *                            last so all state changes are applied first.
 *  12. **restoreFromSaved** – creates a new tab, independent of existing tabs;
 *                            safe to do at the very end.
 */
export function plan(
  ops: Operation[],
  snapshot: Snapshot,
  extraWindowOps?: WindowOperation[],
): Operation[] {
  // Build a map of tabId → current windowId for move classification
  const tabWindow = new Map<number, number>();
  for (const line of snapshot.lines) {
    if (line.tabId !== null) {
      tabWindow.set(line.tabId, line.windowId);
    }
  }

  // Buckets keyed by stage
  const buckets = new Map<Stage, Operation[]>();
  for (const stage of STAGE_ORDER) {
    buckets.set(stage, []);
  }

  const badKind = (_: never): never => {
    throw new Error("unreachable");
  };

  for (const op of ops) {
    switch (op.kind) {
      case "create":
        buckets.get("create")!.push(op);
        break;

      case "restoreFromSaved":
        buckets.get("restoreFromSaved")!.push(op);
        break;

      case "close":
        buckets.get("close")!.push(op);
        break;

      case "discard":
        buckets.get("discard")!.push(op);
        break;

      case "navigate":
        buckets.get("navigate")!.push(op);
        break;

      case "group":
        buckets.get("group")!.push(op);
        break;

      case "assignFolder":
        buckets.get("assignFolder")!.push(op);
        break;

      case "bookmark":
        buckets.get("bookmark")!.push(op);
        break;

      case "saveForLater":
        buckets.get("saveForLater")!.push(op);
        break;

      case "move": {
        const currentWid = tabWindow.get(op.tabId);
        const isCross = currentWid !== undefined && currentWid !== op.windowId;
        buckets.get(isCross ? "crossWindowMove" : "sameWindowMove")!.push(op);
        break;
      }

      default:
        badKind(op);
    }
  }

  if (extraWindowOps) {
    for (const wop of extraWindowOps) {
      buckets.get("createWindow")!.push(wop as unknown as Operation);
    }
  }

  // Concatenate buckets in stage order
  const result: Operation[] = [];
  for (const stage of STAGE_ORDER) {
    for (const op of buckets.get(stage)!) {
      result.push(op);
    }
  }
  return result;
}
