import { EditorView } from "@codemirror/view";

export const bufferDarkTheme = EditorView.theme({
  "&": { backgroundColor: "#111522", color: "#d8def8" },
  "&.cm-focused": { outline: "none" },
  ".cm-cursor": { borderLeftColor: "#f5bde6", borderLeftWidth: "2px" },
  ".cm-selectionBackground, &.cm-focused .cm-selectionBackground": { backgroundColor: "#34466f !important" },
  ".cm-gutters": {
    backgroundColor: "#111522",
    color: "#4e5778",
    border: "none",
    borderRight: "1px solid rgba(126, 145, 196, .12)",
  },
  ".cm-lineNumbers .cm-gutterElement": { padding: "0 8px 0 16px", fontSize: "11px" },
  ".cm-activeLineGutter": { backgroundColor: "rgba(138, 173, 244, .08)", color: "#9aa6cf" },
  ".cm-activeLine": { backgroundColor: "rgba(138, 173, 244, .055)" },
  ".cm-headerLine": { backgroundColor: "#202b45", color: "#d8def8", fontWeight: 600 },
  ".cm-sectionLine": { color: "#a5b4e8", fontWeight: 600 },
  ".cm-urlMuted": { color: "#697398" },
  ".cm-headerLine .cm-lineNumbers .cm-gutterElement": { backgroundColor: "#202b45", color: "#d8def8" },
  ".cm-nonEditable": { opacity: 0.62, pointerEvents: "none" },
  "img.cm-favicon": { width: "16px", height: "16px", verticalAlign: "middle", marginRight: "7px", marginLeft: "2px", borderRadius: "4px" },
  "span.cm-favicon-placeholder": { display: "inline-block", backgroundColor: "#3d4b73", width: "16px", height: "16px", verticalAlign: "middle", marginRight: "7px", marginLeft: "2px", borderRadius: "4px" },
  "&.cm-focused .cm-cursorLayer .cm-cursor": { visibility: "visible" },
  ".cm-selectionMatch": { backgroundColor: "#34466f" },
  ".cm-selectionLayer .cm-selectionBackground": { backgroundColor: "#34466f" },
  ".cm-searchMatch": { backgroundColor: "#3d4b73", outline: "1px solid #697398" },
  ".cm-searchMatch.selected": { backgroundColor: "#34466f" },
  ".cm-scroller": { fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'SF Mono', 'Menlo', monospace", fontSize: "13px", lineHeight: "1.7" },
  ".cm-content": { caretColor: "#f5bde6", padding: "16px 0 24px" },
  ".cm-line": { padding: "3px 28px 3px 10px" },
  ".cm-panels": { backgroundColor: "#151a2b", color: "#a9b1d6", border: "1px solid #34466f" },
  ".cm-panels input": { backgroundColor: "#080a12", color: "#d8def8", border: "1px solid #34466f", fontFamily: "'JetBrains Mono', monospace", fontSize: "13px" },
  ".cm-panels label": { color: "#a9b1d6", fontFamily: "'JetBrains Mono', monospace", fontSize: "13px" },
}, { dark: true });
